[params.hugopress.modules.video-js.hooks.head-end]

[params.hugopress.modules.video-js.hooks.body-end]

[params.video_js]
css_url = "https://unpkg.com/video.js/dist/video-js.min.css"
js_url = "https://unpkg.com/video.js/dist/video.min.js"
lang_js_url = "https://unpkg.com/video.js/dist/lang/%s.js"
playback_rates = [0.5, 1, 1.5, 2]
# skip_forward = 5 # 5, 10 or 30.
# skip_backward = 5 # 5, 10 or 30.
